/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hash.Table;

public class App {


    public static void main(String[] args) {

HashTable m=new HashTable(5);
m.push(15,"osama");
m.push(4,"Alli");
m.push(2,"Mohammad");
m.push(3,"OQlah");
m.push(14,"14444");
m.push(15,"15555");
m.push(16,"16666");
m.push(17,"17777");
m.push(18,"18888");

try {
    System.out.println(m.get(20));//item not found

    System.out.println(m.contains(18));
}catch (Exception e){
    e.printStackTrace();
}
//m.printArray();
//        System.out.println(m.toString());

    }
}
