/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       LinkedList l1=new LinkedList();
        l1.insert(1);
        l1.insert(2);
        l1.insert(3);
        l1.insert(4);
        l1.insert(5);
        l1.print();

        System.out.println(l1.toString());
    }
}
