/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       LinkedList l1=new LinkedList();
        l1.append(1);
        l1.append(2);
        l1.append(3);
        LinkedList l2=new LinkedList();
        l2.append(5);
        l2.append(6);

        /////// uncomment the below statmenit to show result When list 2 is grater than list 1

//        l2.append(7);
//        l2.append(8);
//        l2.append(9);



LinkedList l3= new LinkedList();



        System.out.println(l1.toString());
        System.out.println(l2.toString());
try {
    l3= l3.zipLists( l1, l2 );
    System.out.println("Ziplist: "+l3.toString());

}catch (Exception e){
    e.printStackTrace();
}

//        System.out.println(l1.size());
//        System.out.println("KTH "+l1.kth(2));
//        System.out.println(l1.palinderom());


//l1.print();
//l1.insertAfter(2,10);
//        l1.insertAfter(10,8);
//        System.out.println(l1.toString());
//
//        l1.insertBefor(1,333);
//        System.out.println("inserBefor Linklist "+l1.toString());
    }
}
