/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import java.lang.reflect.Array;
import java.util.Arrays;

public class App {

    public static int[] sort(int []arr){
        int k;
        int temp;
        for (int i=1; i< arr.length;i++) {
                k = arr[i];
                temp = i;
                while (temp > 0 && (arr[temp - 1] > k)) {
                        k = arr[temp];
                        arr[temp] = arr[temp - 1];
                        arr[temp - 1] = k;
                     --temp;
                    }

        }
        return arr;
    }

    public static void main(String[] args) {

int []ar={7,4,6,5,9,8,2,1};
        System.out.println(Arrays.toString(sort(ar)));

    }
}
