/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }

    @Test void testCreate(){
        LinkedList l2=new LinkedList();
        String listIsCreating="list is Empty";
        assertEquals(listIsCreating,l2.toString());
    }
    @Test void insert(){
        LinkedList l2=new LinkedList();
        l2.insert(2);

        boolean empty;
        empty = false;

        assertEquals(empty,l2.checkEmpty());
    }
    @Test void  head(){
        LinkedList l3=new LinkedList();
        l3.insert(2);

        int expected=2;

        assertEquals(expected,l3.head.value);
    }
    @Test void multiple(){
        LinkedList l2=new LinkedList();
        l2.insert(1);
        l2.insert(2);

        String expected="{2}->{1}->NULL";

        assertEquals(expected,l2.toString());

    }
    @Test void checkVlaueTrue(){
        LinkedList l2=new LinkedList();
        l2.insert(1);
        l2.insert(2);
        l2.insert(3);
        l2.insert(4);

        boolean expected;
        expected = true;

        assertEquals(expected,l2.includes(3));
    }
    @Test void checkVlaueFalse(){
        LinkedList l2=new LinkedList();
        l2.insert(1);
        l2.insert(2);

        l2.insert(4);

        boolean found;
        found = false;

        assertEquals(found,l2.includes(3));
    }

    @Test void retrunCollection(){
        LinkedList l2=new LinkedList();
        l2.insert(1);
        l2.insert(2);
        l2.insert(3);
        l2.insert(4);
        l2.insert(5);

        String expected="{5}->{4}->{3}->{2}->{1}->NULL";

        assertEquals(expected,l2.toString());

    }
}
