/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hash.Table;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test  void  add(){
        HashTable m=new HashTable(5);
        m.push(10,"osama111");
        String out="osama111";
        assertEquals(out,m.get(10));

        // Successfully returns null for a key that does not exist in the hashtable

        String out1= "item not Found";
        assertEquals(out1,m.get(15));
    }
}
